#! /usr/local/bin/python

#Declare variables 
DNA_sequence = "CTTTGAGTGCTTTATCGAGTGTCCCATTGACTCCGCCGCCAATTATATATGAGCGCCGACTACTAACTGCTTCGTTCGTTTCAAATAGTTCGGCCGATACTCATCAGCTGGTTATGACAGTCGTTGGTCGAAGCGGTCGCGCGATCACACATCCACTTTGATGATGCCGGCTTGATGGCTTTGGAAATGGCCACATTGTCACTTATATTCTGGGCATAGTGTGTTGTAGATATGTGTATACCTAACGCGCGTGACCGTGGTTTGCCCCGGTTGAAGAACGGGCATGGGGAAAATGGGACAAGTCTTAAGGGATATCCATGAATCCATCGAAGATCGCCGAAGATTCACCACTATAGATGATTAACTATTTGTGGTGAGCGTCAGCCGTCGAAGCCGAAGTGCCGTTCGTCACGAGTCAAACTCCAGAAGCGGTCTGCGGCGCTTCGCGTCTTATCACTTCTCGTTAGTGGCGTGACCGCGCCTTCTAGTCGCCTTGACTTTTTGTTGCGGCTAACCAGACAGTTGACGTGACGGGCCGAGCACTGATCTACATGGTATCCGCGGCGATCGTAGTGTTGATCCGACTTGAGTTCCGTTTAGCGACCACGCGATCAAAAGTCGGCCCACCTCTCGTTTTTTGACTCCCAGGAACGACATGATAAGCGGTATCGCCTTCGATTGTTGAACCAGCTGCTGTTAAAAGGTCATGGGCGCTTATGAACCCAGACATTGTGTCGTCGTAGTGAACGTTTAAGTTTAAAATCCCTTTTCGCTGTCCTTATCCACCCGGGTCAAAAGGCGGCTCCTTACGCACTCGTGAGCTAGATTATGATGGTGAGAAGCAGGCACAGATGAGACAATATACGTACAATACGTCATGGGGTTCGCTTAATCTTTGATGGGAATTTCTGGTCTAATTTATCAGACTGCCGTGGCGTGAGAGT"
nucleotides = "A T G C"
dict_of_nucleotides = {}

#Split the nucleotides on the space and store the nucleotide in i. 
# i.e. the first value i will contain is A then T etc.
for  i in nucleotides.split():
 
    #Count how many times the nucleotide stored in i is found in the DNA sequence 
    # and store that number in count_nucleotide.
    count_nucleotide = DNA_sequence.count(i)
    #Store the nucleotide as the key in the dictionary 
    # and the occurence of the nucleotide as the value.
    dict_of_nucleotides[i] = count_nucleotide

#Print out the nuleotides and occurence in the DNA_sequence. 
print(dict_of_nucleotides)
